version: '3.8'
services:
  ecom-shop-api:
    environment:
      - MONGO=mongodb+srv://edwardduong:anhden11@ecom-shop.pqzstr4.mongodb.net/?retryWrites=true&w=majority
    build:
      context: .
      dockerfile: express.Dockerfile
    volumes:
      - ./:/usr/app
    container_name: ecom-shop-api
    ports:
      - 5000:5000
    command: node index.js
    networks:
      - mongodb_network

  ecom-shop-client:
    build: 
      context: .
      dockerfile: client.Dockerfile
    container_name: ecom-shop-client
    network_mode: host
    ports:
      - 80:80
    depends_on:
      - ecom-shop-api

volumes:
  mongodb:

networks:
  mongodb_network:
    name: mongodb_network