version: '3.8'
services:
  ecom-shop-api:
    environment:
      - MONGO=mongodb+srv://edwardduong:anhden11@ecom-shop.pqzstr4.mongodb.net/?retryWrites=true&w=majority
    build:
      context: .
      dockerfile: express.Dockerfile
    volumes:
      - ./:/usr/app
    container_name: ecom-shop-api
    ports:
      - 5000:5000
    command: node index.js
    networks:
      - ecom_network
  client:
    build: 
      context: .
      dockerfile: client.prod.Dockerfile
    container_name: ecom-shop-client
    # ports:
    #   - 80:80
    depends_on:
      - ecom-shop-api
    networks:
      - ecom_network
  
  proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    container_name: proxy
    ports: 
      - 80:80
    depends_on:
      - client
      - ecom-shop-api
    networks:
      - ecom_network

networks:
  ecom_network:
    name: ecom_network
